// prettier-ignore
export const PUZZLES = [
  ['hydro,islet,balmy,candy,copse', 'aobly,ielet,dhrcy,masyd,copns'],
  ['bread,magma,anvil,stork,gloat', 'blegg,mmaat,tvnio,saork,drlaa'],
  ['feast,winch,buyer,would,giant', 'fitlt,nench,yubre,aodsu,giwwa'],
  ['state,igloo,elegy,agony,voila', 'ltati,ggyvo,leeol,aiyno,ogesa'],
  ['angst,reuse,suing,glide,brave', 'eegru,sbtse,iulng,risdn,egava'],
  ['pizza,bacon,sauce,curds,crust', 'sucsc,uaudn,pabae,zcros,crizt', 'food'],
  ['herbs,thyme,onion,basil,chard', 'hnobh,ssyce,oeirr,bdtil,mahna', 'food'],
  ['', '', 'love'], // TODO: valentines day
  ['swine,rhino,tapir,fitch,zebra', 'pwhnr,riiaf,easre,otich,ztbin', 'animals'],
  ['koala,steer,horse,lemur,tiger', 'eomrl,htkei,surse,agaol,treer', 'animals'],
  ['china,india,japan,napal,yemen', 'cjaae,iadpn,hapnn,aniil,namey', 'countries'],
  ['spain,samoa,qatar,syria,italy', 'satmr,riiop,laaas,yynia,ataqs', 'countries'],
  ['bagel,cream,caper,seeds,toast', 'ragtt,cbeea,odpee,sraas,ecmsl', 'food'],
  ['sushi,knife,algae,trout,gills', 'gnsti,luioe,rlgat,eafsh,silku', 'food'],
  ['space,phase,probe,cloak,prime', 'srrke,bhesm,ppopa,olcac,eaiep', 'starrek'],
  ['spock,riker,quark,seven,phlox', 'qiokc,lpksr,sraun,eevek,xhrop', 'starrek'],
  ['chimp,sheep,tabby,panda,bison', 'eboma,pehcp,tadhb,spnba,yisin', 'animals'],
  ['sloth,hippo,camel,shrew,moose', 'lseph,hsptl,caheo,emosw,morio', 'animals'],
  ['melon,apple,grape,peach,lemon', 'megeo,pmelp,leapo,arach,lnpne', 'fruit'],
  ['limes,berry,kiwis,pears,mango', 'kieei,amrsy,liwsr,pgbns,oarem', 'fruit'],
  ['wires,chain,board,plane,knife', 'pfnec,shnda,noaii,wlare,kbrie', 'tools'],
  ['screw,nails,drill,bolts,bench', 'bnrba,cwirs,dlihl,eoets,slcnl', 'tools'],
  ['blues,swing,metal,salsa,disco', 'buums,itiac,ehwnl,eolse,ossgd', 'music'],
  ['urban,samba,house,dance,indie', 'uosen,bueba,irada,eancd,hnsim', 'music'],
  ['bruce,peggy,clint,bucky,shuri', 'ckcbe,yeigp,crihb,tuury,snulg', 'marvel'],
  ['widow,peter,stark,quill,carol', 'lodea,poter,ltwli,ruksr,caqiw', 'marvel'],
  ['drink,latte,break,beans,steam', 'kannb,lemse,traad,keais,tbert', 'coffee'],
  ['mocha,irish,cream,sugar,brown', 'manis,hriar,rrwom,bugah,scoec', 'coffee'],
  ['whale,llama,skunk,hyena,mouse', 'wknly,elsms,ahmnh,keeaa,uoual', 'animals'],
  ['sable,stoat,otter,puppy,dingo', 'tirle,sspto,ytaeb,pnpoo,daugt', 'animals'],
  ['honda,tesla,chevy,buick,acura', 'henul,ucsaa,hcoay,bdicr,aetkv', 'cars'],
  ['dodge,lexus,mazda,scion,volvo', 'dogdi,mvaaz,lxsdu,csvon,eoleo', 'cars'],
  ['argon,noble,joule,flask,bonds', 'nfgjn,aobds,olalb,rouek,eonls', 'chemistry'],
  ['alloy,boron,atoms,radon,xenon', 'obeoa,losdn,ynomr,naoan,xltor', 'chemistry'],
]

export const WORDS = [
  'aback',
  'abase',
  'abate',
  'abbey',
  'abbot',
  'abhor',
  'abide',
  'abled',
  'abode',
  'abort',
  'about',
  'above',
  'abuse',
  'abyss',
  'acorn',
  'acrid',
  'actor',
  'acute',
  'adage',
  'adapt',
  'adept',
  'admin',
  'admit',
  'adobe',
  'adopt',
  'adore',
  'adorn',
  'adult',
  'affix',
  'afire',
  'afoot',
  'afoul',
  'after',
  'again',
  'agape',
  'agate',
  'agent',
  'agile',
  'aging',
  'aglow',
  'agony',
  'agora',
  'agree',
  'ahead',
  'aider',
  'aisle',
  'alarm',
  'album',
  'alert',
  'algae',
  'alibi',
  'alien',
  'align',
  'alike',
  'alive',
  'allay',
  'alley',
  'allot',
  'allow',
  'alloy',
  'aloft',
  'alone',
  'along',
  'aloof',
  'aloud',
  'alpha',
  'altar',
  'alter',
  'amass',
  'amaze',
  'amber',
  'amble',
  'amend',
  'amiss',
  'amity',
  'among',
  'ample',
  'amply',
  'amuse',
  'angel',
  'anger',
  'angle',
  'angry',
  'angst',
  'anime',
  'ankle',
  'annex',
  'annoy',
  'annul',
  'anode',
  'antic',
  'anvil',
  'aorta',
  'apart',
  'aphid',
  'aping',
  'apnea',
  'apple',
  'apply',
  'apron',
  'aptly',
  'arbor',
  'ardor',
  'arena',
  'argue',
  'arise',
  'armor',
  'aroma',
  'arose',
  'array',
  'arrow',
  'arson',
  'artsy',
  'ascot',
  'ashen',
  'aside',
  'askew',
  'assay',
  'asset',
  'atoll',
  'atone',
  'attic',
  'audio',
  'audit',
  'augur',
  'aunty',
  'avail',
  'avert',
  'avian',
  'avoid',
  'await',
  'awake',
  'award',
  'aware',
  'awash',
  'awful',
  'awoke',
  'axial',
  'axiom',
  'axion',
  'azure',
  'bacon',
  'badge',
  'badly',
  'bagel',
  'baggy',
  'baker',
  'baler',
  'balmy',
  'banal',
  'banjo',
  'barge',
  'baron',
  'basal',
  'basic',
  'basil',
  'basin',
  'basis',
  'baste',
  'batch',
  'bathe',
  'baton',
  'batty',
  'bawdy',
  'bayou',
  'beach',
  'beady',
  'beard',
  'beast',
  'beech',
  'beefy',
  'befit',
  'began',
  'begat',
  'beget',
  'begin',
  'begun',
  'being',
  'belch',
  'belie',
  'belle',
  'belly',
  'below',
  'bench',
  'beret',
  'berry',
  'berth',
  'beset',
  'betel',
  'bevel',
  'bezel',
  'bible',
  'bicep',
  'biddy',
  'bigot',
  'bilge',
  'billy',
  'binge',
  'bingo',
  'biome',
  'birch',
  'birth',
  'bison',
  'bitty',
  'black',
  'blade',
  'blame',
  'bland',
  'blank',
  'blare',
  'blast',
  'blaze',
  'bleak',
  'bleat',
  'bleed',
  'bleep',
  'blend',
  'bless',
  'blimp',
  'blind',
  'blink',
  'bliss',
  'blitz',
  'bloat',
  'block',
  'bloke',
  'blond',
  'blood',
  'bloom',
  'blown',
  'bluer',
  'bluff',
  'blunt',
  'blurb',
  'blurt',
  'blush',
  'board',
  'boast',
  'bobby',
  'boney',
  'bongo',
  'bonus',
  'booby',
  'boost',
  'booth',
  'booty',
  'booze',
  'boozy',
  'borax',
  'borne',
  'bosom',
  'bossy',
  'botch',
  'bough',
  'boule',
  'bound',
  'bowel',
  'boxer',
  'brace',
  'braid',
  'brain',
  'brake',
  'brand',
  'brash',
  'brass',
  'brave',
  'bravo',
  'brawl',
  'brawn',
  'bread',
  'break',
  'breed',
  'briar',
  'bribe',
  'brick',
  'bride',
  'brief',
  'brine',
  'bring',
  'brink',
  'briny',
  'brisk',
  'broad',
  'broil',
  'broke',
  'brood',
  'brook',
  'broom',
  'broth',
  'brown',
  'brunt',
  'brush',
  'brute',
  'buddy',
  'budge',
  'buggy',
  'bugle',
  'build',
  'built',
  'bulge',
  'bulky',
  'bully',
  'bunch',
  'bunny',
  'burly',
  'burnt',
  'burst',
  'bused',
  'bushy',
  'butte',
  'buxom',
  'buyer',
  'bylaw',
  'cabal',
  'cabby',
  'cabin',
  'cable',
  'cacao',
  'cache',
  'cacti',
  'caddy',
  'cadet',
  'cagey',
  'cairn',
  'camel',
  'cameo',
  'canal',
  'candy',
  'canny',
  'canoe',
  'canon',
  'caper',
  'caput',
  'carat',
  'cargo',
  'carol',
  'carry',
  'carve',
  'caste',
  'catch',
  'cater',
  'catty',
  'caulk',
  'cause',
  'cavil',
  'cease',
  'cedar',
  'cello',
  'chafe',
  'chaff',
  'chain',
  'chair',
  'chalk',
  'champ',
  'chant',
  'chaos',
  'chard',
  'charm',
  'chart',
  'chase',
  'chasm',
  'cheap',
  'cheat',
  'check',
  'cheek',
  'cheer',
  'chess',
  'chest',
  'chick',
  'chide',
  'chief',
  'child',
  'chili',
  'chill',
  'chime',
  'china',
  'chirp',
  'chock',
  'choir',
  'choke',
  'chord',
  'chore',
  'chose',
  'chuck',
  'chump',
  'chunk',
  'churn',
  'chute',
  'cider',
  'cigar',
  'cinch',
  'circa',
  'civic',
  'civil',
  'clack',
  'claim',
  'clamp',
  'clang',
  'clank',
  'clash',
  'clasp',
  'class',
  'clean',
  'clear',
  'cleat',
  'cleft',
  'clerk',
  'click',
  'cliff',
  'climb',
  'cling',
  'clink',
  'cloak',
  'clock',
  'clone',
  'close',
  'cloth',
  'cloud',
  'clout',
  'clove',
  'clown',
  'cluck',
  'clued',
  'clump',
  'clung',
  'coach',
  'coast',
  'cobra',
  'cocoa',
  'colon',
  'color',
  'comet',
  'comfy',
  'comic',
  'comma',
  'conch',
  'condo',
  'conic',
  'copse',
  'coral',
  'corer',
  'corny',
  'couch',
  'cough',
  'could',
  'count',
  'coupe',
  'court',
  'coven',
  'cover',
  'covet',
  'covey',
  'cower',
  'coyly',
  'crack',
  'craft',
  'cramp',
  'crane',
  'crank',
  'crash',
  'crass',
  'crate',
  'crave',
  'crawl',
  'craze',
  'crazy',
  'creak',
  'cream',
  'credo',
  'creed',
  'creek',
  'creep',
  'creme',
  'crepe',
  'crept',
  'cress',
  'crest',
  'crick',
  'cried',
  'crier',
  'crime',
  'crimp',
  'crisp',
  'croak',
  'crock',
  'crone',
  'crony',
  'crook',
  'cross',
  'croup',
  'crowd',
  'crown',
  'crude',
  'cruel',
  'crumb',
  'crump',
  'crush',
  'crust',
  'crypt',
  'cubic',
  'cumin',
  'curio',
  'curly',
  'curry',
  'curse',
  'curve',
  'curvy',
  'cutie',
  'cyber',
  'cycle',
  'cynic',
  'daddy',
  'daily',
  'dairy',
  'daisy',
  'dally',
  'dance',
  'dandy',
  'datum',
  'daunt',
  'dealt',
  'death',
  'debar',
  'debit',
  'debug',
  'debut',
  'decal',
  'decay',
  'decor',
  'decoy',
  'decry',
  'defer',
  'deign',
  'deity',
  'delay',
  'delta',
  'delve',
  'demon',
  'demur',
  'denim',
  'dense',
  'depot',
  'depth',
  'derby',
  'deter',
  'detox',
  'deuce',
  'devil',
  'diary',
  'dicey',
  'digit',
  'dilly',
  'dimly',
  'diner',
  'dingo',
  'dingy',
  'diode',
  'dirge',
  'dirty',
  'disco',
  'ditch',
  'ditto',
  'ditty',
  'diver',
  'dizzy',
  'dodge',
  'dodgy',
  'dogma',
  'doing',
  'dolly',
  'donor',
  'donut',
  'dopey',
  'doubt',
  'dough',
  'dowdy',
  'dowel',
  'downy',
  'dowry',
  'dozen',
  'draft',
  'drain',
  'drake',
  'drama',
  'drank',
  'drape',
  'drawl',
  'drawn',
  'dread',
  'dream',
  'dress',
  'dried',
  'drier',
  'drift',
  'drill',
  'drink',
  'drive',
  'droit',
  'droll',
  'drone',
  'drool',
  'droop',
  'dross',
  'drove',
  'drown',
  'druid',
  'drunk',
  'dryer',
  'dryly',
  'duchy',
  'dully',
  'dummy',
  'dumpy',
  'dunce',
  'dusky',
  'dusty',
  'dutch',
  'duvet',
  'dwarf',
  'dwell',
  'dwelt',
  'dying',
  'eager',
  'eagle',
  'early',
  'earth',
  'easel',
  'eaten',
  'eater',
  'ebony',
  'eclat',
  'edict',
  'edify',
  'eerie',
  'egret',
  'eight',
  'eject',
  'eking',
  'elate',
  'elbow',
  'elder',
  'elect',
  'elegy',
  'elfin',
  'elide',
  'elite',
  'elope',
  'elude',
  'email',
  'embed',
  'ember',
  'emcee',
  'empty',
  'enact',
  'endow',
  'enema',
  'enemy',
  'enjoy',
  'ennui',
  'ensue',
  'enter',
  'entry',
  'envoy',
  'epoch',
  'epoxy',
  'equal',
  'equip',
  'erase',
  'erect',
  'erode',
  'error',
  'erupt',
  'essay',
  'ester',
  'ether',
  'ethic',
  'ethos',
  'etude',
  'evade',
  'event',
  'every',
  'evict',
  'evoke',
  'exact',
  'exalt',
  'excel',
  'exert',
  'exile',
  'exist',
  'expel',
  'extol',
  'extra',
  'exult',
  'eying',
  'fable',
  'facet',
  'faint',
  'fairy',
  'faith',
  'false',
  'fancy',
  'fanny',
  'farce',
  'fatal',
  'fatty',
  'fault',
  'fauna',
  'favor',
  'feast',
  'feign',
  'fella',
  'felon',
  'femme',
  'femur',
  'fence',
  'feral',
  'ferry',
  'fetal',
  'fetch',
  'fetid',
  'fetus',
  'fever',
  'fewer',
  'fiber',
  'fibre',
  'ficus',
  'field',
  'fiend',
  'fiery',
  'fifth',
  'fifty',
  'fight',
  'filer',
  'filet',
  'filly',
  'filmy',
  'filth',
  'final',
  'finch',
  'finer',
  'first',
  'fishy',
  'fixer',
  'fizzy',
  'fjord',
  'flack',
  'flail',
  'flair',
  'flake',
  'flaky',
  'flame',
  'flank',
  'flare',
  'flash',
  'flask',
  'fleck',
  'fleet',
  'flesh',
  'flick',
  'flier',
  'fling',
  'flint',
  'flirt',
  'float',
  'flock',
  'flood',
  'floor',
  'flora',
  'floss',
  'flour',
  'flout',
  'flown',
  'fluff',
  'fluid',
  'fluke',
  'flume',
  'flung',
  'flunk',
  'flush',
  'flute',
  'flyer',
  'foamy',
  'focal',
  'focus',
  'foggy',
  'foist',
  'folio',
  'folly',
  'foray',
  'force',
  'forge',
  'forgo',
  'forte',
  'forth',
  'forty',
  'forum',
  'found',
  'foyer',
  'frail',
  'frame',
  'frank',
  'fraud',
  'freak',
  'freed',
  'freer',
  'fresh',
  'friar',
  'fried',
  'frill',
  'frisk',
  'fritz',
  'frock',
  'frond',
  'front',
  'frost',
  'froth',
  'frown',
  'froze',
  'fruit',
  'fudge',
  'fugue',
  'fully',
  'fungi',
  'funky',
  'funny',
  'furor',
  'furry',
  'fussy',
  'fuzzy',
  'gaffe',
  'gaily',
  'gamer',
  'gamma',
  'gamut',
  'gassy',
  'gaudy',
  'gauge',
  'gaunt',
  'gauze',
  'gavel',
  'gawky',
  'gayer',
  'gayly',
  'gazer',
  'gecko',
  'geeky',
  'geese',
  'genie',
  'genre',
  'ghost',
  'ghoul',
  'giant',
  'giddy',
  'gipsy',
  'girly',
  'girth',
  'given',
  'giver',
  'glade',
  'gland',
  'glare',
  'glass',
  'glaze',
  'gleam',
  'glean',
  'glide',
  'glint',
  'gloat',
  'globe',
  'gloom',
  'glory',
  'gloss',
  'glove',
  'glyph',
  'gnash',
  'gnome',
  'godly',
  'going',
  'golem',
  'golly',
  'gonad',
  'goner',
  'goody',
  'gooey',
  'goofy',
  'goose',
  'gorge',
  'gouge',
  'gourd',
  'grace',
  'grade',
  'graft',
  'grail',
  'grain',
  'grand',
  'grant',
  'grape',
  'graph',
  'grasp',
  'grass',
  'grate',
  'grave',
  'gravy',
  'graze',
  'great',
  'greed',
  'green',
  'greet',
  'grief',
  'grill',
  'grime',
  'grimy',
  'grind',
  'gripe',
  'groan',
  'groin',
  'groom',
  'grope',
  'gross',
  'group',
  'grout',
  'grove',
  'growl',
  'grown',
  'gruel',
  'gruff',
  'grunt',
  'guard',
  'guava',
  'guess',
  'guest',
  'guide',
  'guild',
  'guile',
  'guilt',
  'guise',
  'gulch',
  'gully',
  'gumbo',
  'gummy',
  'guppy',
  'gusto',
  'gusty',
  'habit',
  'hairy',
  'halve',
  'handy',
  'happy',
  'hardy',
  'harpy',
  'harry',
  'harsh',
  'haste',
  'hasty',
  'hatch',
  'hater',
  'haunt',
  'haute',
  'haven',
  'havoc',
  'hazel',
  'heady',
  'heard',
  'heart',
  'heath',
  'heave',
  'heavy',
  'hedge',
  'hefty',
  'heist',
  'helix',
  'hello',
  'hence',
  'heron',
  'hilly',
  'hinge',
  'hippo',
  'hippy',
  'hitch',
  'hoard',
  'hobby',
  'hoist',
  'holly',
  'homer',
  'honey',
  'honor',
  'horde',
  'horse',
  'hotel',
  'hotly',
  'hound',
  'house',
  'hovel',
  'hover',
  'howdy',
  'human',
  'humid',
  'humor',
  'humph',
  'humus',
  'hunch',
  'hunky',
  'hurry',
  'husky',
  'hutch',
  'hydro',
  'hyena',
  'hymen',
  'hyper',
  'icily',
  'icing',
  'ideal',
  'idiom',
  'idiot',
  'idler',
  'idyll',
  'igloo',
  'iliac',
  'image',
  'imbue',
  'impel',
  'imply',
  'inane',
  'inbox',
  'incur',
  'index',
  'inept',
  'inert',
  'infer',
  'ingot',
  'inlay',
  'inlet',
  'inner',
  'input',
  'inter',
  'intro',
  'ionic',
  'irate',
  'irony',
  'islet',
  'issue',
  'itchy',
  'ivory',
  'jaunt',
  'jazzy',
  'jelly',
  'jerky',
  'jetty',
  'jewel',
  'jiffy',
  'joint',
  'joist',
  'joker',
  'jolly',
  'joust',
  'judge',
  'juice',
  'juicy',
  'jumbo',
  'jumpy',
  'junta',
  'junto',
  'juror',
  'kappa',
  'karma',
  'kayak',
  'kebab',
  'khaki',
  'kinky',
  'kiosk',
  'kitty',
  'knack',
  'knave',
  'knead',
  'kneed',
  'kneel',
  'knelt',
  'knife',
  'knock',
  'knoll',
  'known',
  'koala',
  'krill',
  'label',
  'labor',
  'laden',
  'ladle',
  'lager',
  'lance',
  'lanky',
  'lapel',
  'lapse',
  'large',
  'larva',
  'lasso',
  'latch',
  'later',
  'lathe',
  'latte',
  'laugh',
  'layer',
  'leach',
  'leafy',
  'leaky',
  'leant',
  'leapt',
  'learn',
  'lease',
  'leash',
  'least',
  'leave',
  'ledge',
  'leech',
  'leery',
  'lefty',
  'legal',
  'leggy',
  'lemon',
  'lemur',
  'leper',
  'level',
  'lever',
  'libel',
  'liege',
  'light',
  'liken',
  'lilac',
  'limbo',
  'limit',
  'linen',
  'liner',
  'lingo',
  'lipid',
  'lithe',
  'liver',
  'livid',
  'llama',
  'loamy',
  'loath',
  'lobby',
  'local',
  'locus',
  'lodge',
  'lofty',
  'logic',
  'login',
  'loopy',
  'loose',
  'lorry',
  'loser',
  'louse',
  'lousy',
  'lover',
  'lower',
  'lowly',
  'loyal',
  'lucid',
  'lucky',
  'lumen',
  'lumpy',
  'lunar',
  'lunch',
  'lunge',
  'lupus',
  'lurch',
  'lurid',
  'lusty',
  'lying',
  'lymph',
  'lynch',
  'lyric',
  'macaw',
  'macho',
  'macro',
  'madam',
  'madly',
  'mafia',
  'magic',
  'magma',
  'maize',
  'major',
  'maker',
  'mambo',
  'mamma',
  'manga',
  'mange',
  'mango',
  'mangy',
  'mania',
  'manic',
  'manly',
  'manor',
  'maple',
  'march',
  'marry',
  'marsh',
  'mason',
  'masse',
  'match',
  'matey',
  'mauve',
  'maxim',
  'maybe',
  'mayor',
  'mealy',
  'meant',
  'meaty',
  'mecca',
  'medal',
  'media',
  'medic',
  'melee',
  'melon',
  'mercy',
  'merge',
  'merit',
  'merry',
  'metal',
  'meter',
  'metro',
  'micro',
  'midge',
  'midst',
  'might',
  'milky',
  'mimic',
  'mince',
  'miner',
  'minim',
  'minor',
  'minty',
  'minus',
  'mirth',
  'miser',
  'missy',
  'mocha',
  'modal',
  'model',
  'modem',
  'mogul',
  'moist',
  'molar',
  'moldy',
  'money',
  'month',
  'moody',
  'moose',
  'moral',
  'moron',
  'morph',
  'mossy',
  'motel',
  'motif',
  'motor',
  'motto',
  'moult',
  'mound',
  'mount',
  'mourn',
  'mouse',
  'mouth',
  'mover',
  'movie',
  'mower',
  'mucky',
  'mucus',
  'muddy',
  'mulch',
  'mummy',
  'munch',
  'mural',
  'murky',
  'mushy',
  'music',
  'musky',
  'musty',
  'myrrh',
  'nadir',
  'naive',
  'nanny',
  'nasal',
  'nasty',
  'natal',
  'naval',
  'navel',
  'needy',
  'neigh',
  'nerdy',
  'nerve',
  'never',
  'newer',
  'newly',
  'nicer',
  'niche',
  'niece',
  'night',
  'ninja',
  'ninny',
  'ninth',
  'noble',
  'nobly',
  'noise',
  'noisy',
  'nomad',
  'noose',
  'north',
  'nosey',
  'notch',
  'novel',
  'nudge',
  'nurse',
  'nutty',
  'nylon',
  'nymph',
  'oaken',
  'obese',
  'occur',
  'ocean',
  'octal',
  'octet',
  'odder',
  'oddly',
  'offal',
  'offer',
  'often',
  'olden',
  'older',
  'olive',
  'ombre',
  'omega',
  'onion',
  'onset',
  'opera',
  'opine',
  'opium',
  'optic',
  'orbit',
  'order',
  'organ',
  'other',
  'otter',
  'ought',
  'ounce',
  'outdo',
  'outer',
  'outgo',
  'ovary',
  'ovate',
  'overt',
  'ovine',
  'ovoid',
  'owing',
  'owner',
  'oxide',
  'ozone',
  'paddy',
  'pagan',
  'paint',
  'paler',
  'palsy',
  'panel',
  'panic',
  'papal',
  'paper',
  'parer',
  'parka',
  'parry',
  'parse',
  'party',
  'pasta',
  'paste',
  'pasty',
  'patch',
  'patio',
  'patsy',
  'patty',
  'pause',
  'payee',
  'payer',
  'peace',
  'peach',
  'pearl',
  'pecan',
  'pedal',
  'penal',
  'pence',
  'penne',
  'penny',
  'perch',
  'peril',
  'perky',
  'pesky',
  'pesto',
  'petal',
  'petty',
  'phase',
  'phone',
  'phony',
  'photo',
  'piano',
  'picky',
  'piece',
  'piety',
  'piggy',
  'pilot',
  'pinch',
  'piney',
  'pinky',
  'pinto',
  'piper',
  'pique',
  'pitch',
  'pithy',
  'pivot',
  'pixel',
  'pixie',
  'pizza',
  'place',
  'plaid',
  'plain',
  'plait',
  'plane',
  'plank',
  'plant',
  'plate',
  'plaza',
  'plead',
  'pleat',
  'plied',
  'plier',
  'pluck',
  'plumb',
  'plume',
  'plump',
  'plunk',
  'plush',
  'poesy',
  'point',
  'poise',
  'poker',
  'polar',
  'polka',
  'polyp',
  'pooch',
  'poppy',
  'porch',
  'poser',
  'posit',
  'posse',
  'pouch',
  'pound',
  'pouty',
  'power',
  'prank',
  'prawn',
  'preen',
  'press',
  'price',
  'pride',
  'pried',
  'prime',
  'primo',
  'print',
  'prior',
  'prism',
  'privy',
  'prize',
  'probe',
  'prone',
  'prong',
  'proof',
  'prose',
  'proud',
  'prove',
  'prowl',
  'proxy',
  'prude',
  'prune',
  'psalm',
  'pubic',
  'pudgy',
  'puffy',
  'pulpy',
  'pulse',
  'punch',
  'pupal',
  'pupil',
  'puppy',
  'puree',
  'purer',
  'purge',
  'purse',
  'pushy',
  'putty',
  'pygmy',
  'quack',
  'quail',
  'quake',
  'qualm',
  'quark',
  'quart',
  'quash',
  'quasi',
  'queen',
  'queer',
  'quell',
  'query',
  'quest',
  'queue',
  'quick',
  'quiet',
  'quill',
  'quilt',
  'quirk',
  'quite',
  'quota',
  'quote',
  'quoth',
  'rabbi',
  'rabid',
  'racer',
  'radar',
  'radii',
  'radio',
  'rainy',
  'raise',
  'rajah',
  'rally',
  'ralph',
  'ramen',
  'ranch',
  'randy',
  'range',
  'rapid',
  'rarer',
  'raspy',
  'ratio',
  'ratty',
  'raven',
  'rayon',
  'razor',
  'reach',
  'react',
  'ready',
  'realm',
  'rearm',
  'rebar',
  'rebel',
  'rebus',
  'rebut',
  'recap',
  'recur',
  'recut',
  'reedy',
  'refer',
  'refit',
  'regal',
  'rehab',
  'reign',
  'relax',
  'relay',
  'relic',
  'remit',
  'renal',
  'renew',
  'repay',
  'repel',
  'reply',
  'rerun',
  'reset',
  'resin',
  'retch',
  'retro',
  'retry',
  'reuse',
  'revel',
  'revue',
  'rhino',
  'rhyme',
  'rider',
  'ridge',
  'rifle',
  'right',
  'rigid',
  'rigor',
  'rinse',
  'ripen',
  'riper',
  'risen',
  'riser',
  'risky',
  'rival',
  'river',
  'rivet',
  'roach',
  'roast',
  'robin',
  'robot',
  'rocky',
  'rodeo',
  'roger',
  'rogue',
  'roomy',
  'roost',
  'rotor',
  'rouge',
  'rough',
  'round',
  'rouse',
  'route',
  'rover',
  'rowdy',
  'rower',
  'royal',
  'ruddy',
  'ruder',
  'rugby',
  'ruler',
  'rumba',
  'rumor',
  'rupee',
  'rural',
  'rusty',
  'sadly',
  'safer',
  'saint',
  'salad',
  'sally',
  'salon',
  'salsa',
  'salty',
  'salve',
  'salvo',
  'sandy',
  'saner',
  'sappy',
  'sassy',
  'satin',
  'satyr',
  'sauce',
  'saucy',
  'sauna',
  'saute',
  'savor',
  'savoy',
  'savvy',
  'scald',
  'scale',
  'scalp',
  'scaly',
  'scamp',
  'scant',
  'scare',
  'scarf',
  'scary',
  'scene',
  'scent',
  'scion',
  'scoff',
  'scold',
  'scone',
  'scoop',
  'scope',
  'score',
  'scorn',
  'scour',
  'scout',
  'scowl',
  'scram',
  'scrap',
  'scree',
  'screw',
  'scrub',
  'scrum',
  'scuba',
  'sedan',
  'seedy',
  'segue',
  'seize',
  'semen',
  'sense',
  'sepia',
  'serif',
  'serum',
  'serve',
  'setup',
  'seven',
  'sever',
  'sewer',
  'shack',
  'shade',
  'shady',
  'shaft',
  'shake',
  'shaky',
  'shale',
  'shall',
  'shalt',
  'shame',
  'shank',
  'shape',
  'shard',
  'share',
  'shark',
  'sharp',
  'shave',
  'shawl',
  'shear',
  'sheen',
  'sheep',
  'sheer',
  'sheet',
  'sheik',
  'shelf',
  'shell',
  'shied',
  'shift',
  'shine',
  'shiny',
  'shire',
  'shirk',
  'shirt',
  'shoal',
  'shock',
  'shone',
  'shook',
  'shoot',
  'shore',
  'shorn',
  'short',
  'shout',
  'shove',
  'shown',
  'showy',
  'shrew',
  'shrub',
  'shrug',
  'shuck',
  'shunt',
  'shush',
  'shyly',
  'siege',
  'sieve',
  'sight',
  'sigma',
  'silky',
  'silly',
  'since',
  'sinew',
  'singe',
  'siren',
  'sixth',
  'sixty',
  'skate',
  'skier',
  'skiff',
  'skill',
  'skimp',
  'skirt',
  'skulk',
  'skull',
  'skunk',
  'slack',
  'slain',
  'slang',
  'slant',
  'slash',
  'slate',
  'sleek',
  'sleep',
  'sleet',
  'slept',
  'slice',
  'slick',
  'slide',
  'slime',
  'slimy',
  'sling',
  'slink',
  'sloop',
  'slope',
  'slosh',
  'sloth',
  'slump',
  'slung',
  'slunk',
  'slurp',
  'slush',
  'slyly',
  'smack',
  'small',
  'smart',
  'smash',
  'smear',
  'smell',
  'smelt',
  'smile',
  'smirk',
  'smite',
  'smith',
  'smock',
  'smoke',
  'smoky',
  'smote',
  'snack',
  'snail',
  'snake',
  'snaky',
  'snare',
  'snarl',
  'sneak',
  'sneer',
  'snide',
  'sniff',
  'snipe',
  'snoop',
  'snore',
  'snort',
  'snout',
  'snowy',
  'snuck',
  'snuff',
  'soapy',
  'sober',
  'soggy',
  'solar',
  'solid',
  'solve',
  'sonar',
  'sonic',
  'sooth',
  'sooty',
  'sorry',
  'sound',
  'south',
  'sower',
  'space',
  'spade',
  'spare',
  'spark',
  'spasm',
  'spawn',
  'speak',
  'spear',
  'speck',
  'speed',
  'spell',
  'spelt',
  'spend',
  'spent',
  'sperm',
  'spice',
  'spicy',
  'spied',
  'spiel',
  'spike',
  'spiky',
  'spill',
  'spilt',
  'spine',
  'spiny',
  'spire',
  'spite',
  'splat',
  'split',
  'spoil',
  'spoke',
  'spoof',
  'spool',
  'spoon',
  'spore',
  'sport',
  'spout',
  'spray',
  'spree',
  'sprig',
  'spunk',
  'spurn',
  'spurt',
  'squad',
  'squat',
  'squib',
  'stack',
  'staff',
  'stage',
  'staid',
  'stain',
  'stair',
  'stake',
  'stale',
  'stalk',
  'stall',
  'stamp',
  'stand',
  'stank',
  'stare',
  'stark',
  'start',
  'stash',
  'state',
  'stave',
  'stead',
  'steak',
  'steal',
  'steam',
  'steed',
  'steel',
  'steep',
  'steer',
  'stein',
  'stern',
  'stick',
  'stiff',
  'still',
  'stilt',
  'sting',
  'stink',
  'stint',
  'stock',
  'stoic',
  'stoke',
  'stole',
  'stomp',
  'stone',
  'stony',
  'stood',
  'stool',
  'stoop',
  'store',
  'stork',
  'storm',
  'story',
  'stout',
  'stove',
  'strap',
  'straw',
  'stray',
  'strip',
  'strut',
  'stuck',
  'study',
  'stuff',
  'stump',
  'stung',
  'stunk',
  'stunt',
  'style',
  'suave',
  'sugar',
  'suing',
  'suite',
  'sulky',
  'sully',
  'sumac',
  'sunny',
  'super',
  'surer',
  'surge',
  'surly',
  'sushi',
  'swami',
  'swamp',
  'swarm',
  'swash',
  'swath',
  'swear',
  'sweat',
  'sweep',
  'sweet',
  'swell',
  'swept',
  'swift',
  'swill',
  'swine',
  'swing',
  'swirl',
  'swish',
  'swoon',
  'swoop',
  'sword',
  'swore',
  'sworn',
  'swung',
  'synod',
  'syrup',
  'tabby',
  'table',
  'taboo',
  'tacit',
  'tacky',
  'taffy',
  'taint',
  'taken',
  'taker',
  'tally',
  'talon',
  'tamer',
  'tango',
  'tangy',
  'taper',
  'tapir',
  'tardy',
  'tarot',
  'taste',
  'tasty',
  'tatty',
  'taunt',
  'tawny',
  'teach',
  'teary',
  'tease',
  'teddy',
  'teeth',
  'tempo',
  'tenet',
  'tenor',
  'tense',
  'tenth',
  'tepee',
  'tepid',
  'terra',
  'terse',
  'testy',
  'thank',
  'theft',
  'their',
  'theme',
  'there',
  'these',
  'theta',
  'thick',
  'thief',
  'thigh',
  'thing',
  'think',
  'third',
  'thong',
  'thorn',
  'those',
  'three',
  'threw',
  'throb',
  'throw',
  'thrum',
  'thumb',
  'thump',
  'thyme',
  'tiara',
  'tibia',
  'tidal',
  'tiger',
  'tight',
  'tilde',
  'timer',
  'timid',
  'tipsy',
  'titan',
  'tithe',
  'title',
  'toast',
  'today',
  'toddy',
  'token',
  'tonal',
  'tonga',
  'tonic',
  'tooth',
  'topaz',
  'topic',
  'torch',
  'torso',
  'torus',
  'total',
  'totem',
  'touch',
  'tough',
  'towel',
  'tower',
  'toxic',
  'toxin',
  'trace',
  'track',
  'tract',
  'trade',
  'trail',
  'train',
  'trait',
  'trash',
  'trawl',
  'tread',
  'treat',
  'trend',
  'triad',
  'trial',
  'tribe',
  'trice',
  'trick',
  'tried',
  'tripe',
  'trite',
  'troll',
  'troop',
  'trope',
  'trout',
  'trove',
  'truce',
  'truck',
  'truer',
  'truly',
  'trump',
  'trunk',
  'truss',
  'trust',
  'truth',
  'tryst',
  'tubal',
  'tuber',
  'tulip',
  'tulle',
  'tumor',
  'tunic',
  'turbo',
  'tutor',
  'twang',
  'tweak',
  'tweed',
  'tweet',
  'twice',
  'twine',
  'twirl',
  'twist',
  'twixt',
  'tying',
  'udder',
  'ulcer',
  'ultra',
  'umbra',
  'uncle',
  'uncut',
  'under',
  'undid',
  'undue',
  'unfed',
  'unfit',
  'unify',
  'union',
  'unite',
  'unity',
  'unlit',
  'unmet',
  'unset',
  'untie',
  'until',
  'unwed',
  'unzip',
  'upper',
  'upset',
  'urban',
  'urine',
  'usage',
  'usher',
  'using',
  'usual',
  'usurp',
  'utile',
  'utter',
  'vague',
  'valet',
  'valid',
  'valor',
  'value',
  'valve',
  'vapid',
  'vapor',
  'vault',
  'vaunt',
  'vegan',
  'venom',
  'venue',
  'verge',
  'verse',
  'verso',
  'verve',
  'vicar',
  'video',
  'vigil',
  'vigor',
  'villa',
  'vinyl',
  'viola',
  'viper',
  'viral',
  'virus',
  'visit',
  'visor',
  'vista',
  'vital',
  'vivid',
  'vixen',
  'vocal',
  'vodka',
  'vogue',
  'voice',
  'voila',
  'vomit',
  'voter',
  'vouch',
  'vowel',
  'vying',
  'wacky',
  'wafer',
  'wager',
  'wagon',
  'waist',
  'waive',
  'waltz',
  'warty',
  'waste',
  'watch',
  'water',
  'waver',
  'waxen',
  'weary',
  'weave',
  'wedge',
  'weedy',
  'weigh',
  'weird',
  'welch',
  'welsh',
  'wench',
  'whack',
  'whale',
  'wharf',
  'wheat',
  'wheel',
  'whelp',
  'where',
  'which',
  'whiff',
  'while',
  'whine',
  'whiny',
  'whirl',
  'whisk',
  'white',
  'whole',
  'whoop',
  'whose',
  'widen',
  'wider',
  'widow',
  'width',
  'wield',
  'wight',
  'willy',
  'wimpy',
  'wince',
  'winch',
  'windy',
  'wiser',
  'wispy',
  'witch',
  'witty',
  'woken',
  'woman',
  'women',
  'woody',
  'wooer',
  'wooly',
  'woozy',
  'wordy',
  'world',
  'worry',
  'worse',
  'worst',
  'worth',
  'would',
  'wound',
  'woven',
  'wrack',
  'wrath',
  'wreak',
  'wreck',
  'wrest',
  'wring',
  'wrist',
  'write',
  'wrong',
  'wrote',
  'wrung',
  'wryly',
  'yacht',
  'yearn',
  'yeast',
  'yield',
  'young',
  'youth',
  'zebra',
  'zesty',
  'zonal',
]

// const RANDOMS = [
//   ['blitz,tally,lusty,dusky,tibia', 'uliaa,uztlb,lbkty,dtssi,liyyt'],
//   ['brand,fella,epoxy,gayly,mucky', 'xragu,eylla,fopbc,naely,mdyyk'],
//   ['vital,rotor,madam,bayou,knead', 'ontal,tdror,amokm,bayva,aidue'],
//   ['sooth,screw,nymph,video,frown', 'dvrtn,sihew,fompr,ocseo,noywh'],
//   ['favor,stank,stunt,angel,verse', 'fngat,etone,stuar,anvke,vssrl'],
//   ['idiom,paler,humid,spade,motif', 'moidm,pdrel,iueha,sapdm,iitof'],
//   ['eater,count,muddy,occur,stern', 'eatsc,rceny,umtdt,rcouo,edurn'],
//   ['pecan,agent,mound,bulge,guild', 'mecan,nbeau,plgnd,ggoue,utidl'],
//   ['knave,lapse,owner,uncle,fuzzy', 'ankce,lnose,peauz,znvlw,feruy'],
//   ['fleck,floor,spray,tipsy,fiery', 'lfeey,yropp,solaf,iirsk,ftcry'],
//   ['range,drama,shack,affix,showy', 'hyoge,dkimc,fhaar,awsax,srnfa'],
//   ['smoke,blend,sappy,pupal,embed', 'dmpka,elbby,saoed,plpeu,emnps'],
//   ['evade,until,natal,royal,swash', 'atale,ytvin,llnaa,houad,swesr'],
//   ['frame,serif,stead,flown,usurp', 'fsuts,rlrip,omead,wesfn,uearf'],
//   ['seedy,renew,snuff,abhor,frock', 'eendw,usfey,serrn,kchof,froba'],
//   ['reply,handy,taken,taboo,smote', 'snbho,ldnat,yakoe,tapyo,rmete'],
//   ['hyena,glass,mange,thick,claim', 'hmlna,necgs,magst,ehlac,kiaiy'],
//   ['chute,howdy,young,shiny,folly', 'yyote,hufdy,hognu,lnihc,wylso'],
//   ['prone,spire,begun,covey,snuck', 'cnone,srnps,gebur,pcvey,eikou'],
//   ['shown,stone,gummy,egret,block', 'rhoge,ytmne,wloks,ecsnt,buogm'],
//   ['trice,sinew,bushy,trust,grail', 'tricn,rgeuw,byasu,tsehi,irstl'],
//   ['lease,prawn,mimic,druid,chaos', 'lussm,arici,eamnw,dredi,chpoa'],
//   ['place,wield,heave,tonic,topic', 'tlain,ehelo,iwavc,poepc,tdice'],
//   ['forge,leery,skiff,tulip,bitty', 'iorre,iefgk,syyep,ttlff,bltui'],
//   ['refit,enemy,oaken,recap,salve', 'cefma,epvis,eakon,lertn,yaree'],
//   ['flaky,tiger,chuck,haute,jiffy', 'feetu,kigar,yfyck,hajtl,ufihc'],
//   ['weave,credo,ombre,rabid,photo', 'aewee,daemo,tdpiv,rrbrc,bhooo'],
//   ['essay,siege,march,shone,quota', 'qooey,gcesa,maeih,sasnr,eusth'],
//   ['chirp,ninny,story,hyper,clank', 'cnirp,oilyr,tsnye,hnpyr,cnkha'],
//   ['waive,ulcer,flare,pithy,twine', 'taivu,eclep,falye,rewnr,twihi'],
//   ['flute,parry,enter,tepid,pubic', 'elrpp,pauti,ebrft,reeyd,tunic'],
//   ['built,plumb,skier,tithe,shall', 'utilk,plbhe,rtsbs,tiueh,imall'],
//   ['pixie,syrup,acrid,fable,prove', 'oirif,sexud,rcrip,evely,papab'],
//   ['cheer,beast,metro,ember,heist', 'theos,hebts,mrtee,eeamr,beirc'],
//   ['rusty,awash,scare,leapt,delve', 'tusee,awaeh,llras,caepr,dtsvy'],
//   ['nudge,heard,woman,crime,forty', 'egiun,hmcrd,wamoe,arden,froty'],
//   ['aorta,glory,circa,given,posse', 'areic,oigoy,straa,olven,pgscr'],
//   ['brunt,label,steed,pudgy,court', 'uguct,slupa,lteed,ebory,ndbrt'],
//   ['focal,rifle,frost,sedan,sigma', 'noemo,airls,fflgt,ecdrf,sisaa'],
//   ['hater,armor,prune,epoch,tepee', 'eetpr,nrrom,ecuae,eetrh,oppha'],
//   ['creme,lithe,align,mummy,loose', 'cneey,lutmm,slimr,gihee,looam'],
//   ['dried,metal,touch,sneer,sworn', 'oriss,wahet,louct,enner,dmdre'],
//   ['beach,bleak,flake,gravy,jetty', 'btacb,haele,geaal,ftkvy,jkery'],
//   ['grown,argue,graft,fetch,civil', 'ghuee,aggon,rcait,fwtlr,rfvic'],
//   ['blink,arrow,reset,roost,musky', 'blime,arorw,ektrs,ryots,nsuko'],
//   ['poesy,abled,gamma,croup,vomit', 'utaso,abovm,gedma,crypi,elmpo'],
//   ['crypt,clump,femme,prong,corer', 'rcmpc,cleyo,fmemu,nrope,tprgr'],
//   ['intro,bawdy,death,taker,lurch', 'nittb,oacdy,hrard,threk,luewa'],
//   ['scald,pound,tweed,trick,scaly', 'saaeo,rdcns,twlde,tpcuk,dicly'],
//   ['agree,train,robin,small,recur', 'aclre,trini,raban,umolr,ergse'],
//   ['pizza,droll,glove,droop,sepia', 'pdgoa,drrll,zolev,iopzp,ieosa'],
//   ['flora,price,petal,swirl,dowry', 'pollr,faice,tspyr,edirl,wowra'],
//   ['kappa,smack,dryer,emcee,unity', 'packy,teepk,dnyre,emcma,urisa'],
//   ['lefty,dense,adobe,stain,scout', 'uefbs,denso,teitd,saaon,ytelc'],
//   ['chump,basal,grant,sprig,vault', 'crgsp,ivsal,ntagr,mlhbu,aaupt'],
//   ['gayer,cloak,youth,tilde,chant', 'harey,cltdi,yltoe,tkoah,cganu'],
//   ['grope,black,chaff,staid,alter', 'scdha,bkerl,cpaaf,graio,fltet'],
//   ['ditto,tarot,pouty,fence,dwell', 'twtcr,daood,puoty,feltl,tieen'],
//   ['grove,slant,moist,alibi,there', 'otahe,seonr,mgisa,tltei,ivlrb'],
//   ['shock,gamut,ample,solve,nasty', 'chosk,slpsv,ammlt,unate,oagey'],
//   ['nadir,labor,woken,mince,filmy', 'iainn,leobr,wokar,micnf,edmly'],
//   ['qualm,saint,eject,odder,quilt', 'juctd,sodne,tqeal,aimei,qurlt'],
//   ['spied,quote,tract,aisle,uncut', 'cpied,qutoc,uarsl,aintt,usete'],
//   ['chore,sugar,spiel,belly,bench', 'eeoih,seyhp,srrcl,bublg,lenca'],
//   ['larva,bleed,pasta,scope,ether', 'lsrhe,epbae,pasta,arolt,eevdc'],
//   ['stole,drone,gland,vapid,flour', 'rtlog,usdnr,eldno,vafia,plode'],
//   ['their,laden,allow,which,style', 'hleto,llaen,dahrh,cwiwt,siyle'],
//   ['error,onset,stale,pedal,clung', 'elrpo,rnees,ttaan,osdlr,culeg'],
//   ['manor,arose,milky,homer,drool', 'ainor,meoyh,malos,eodrr,morkl'],
//   ['couch,rally,fussy,arise,deity', 'houcc,radfs,lessa,ytyye,luiri'],
//   ['trace,grand,weird,poser,blind', 'driec,onadd,weart,pgesr,lbirn'],
//   ['lobby,spelt,sonar,pooch,scale', 'elbce,hploo,aonsr,potbs,sacly'],
//   ['udder,exert,tumor,freer,swift', 'teeer,oxdrw,imuer,ferdr,sttfu'],
//   ['thumb,detox,retry,reedy,nobly', 'teuyn,rrtoo,ehtey,dredm,bxylb'],
//   ['hasty,caper,lodge,breed,flung', 'eadey,caplr,engge,blths,urfod'],
//   ['river,sieve,maple,fjord,smart', 'stvee,sirve,eafam,pojrr,rmldi'],
//   ['sperm,proud,budge,guard,rowdy', 'ubdrm,drose,pueyd,durrp,aowgg'],
//   ['ratio,brain,altar,ledge,flash', 'terto,blaas,adilr,ralge,fainh'],
//   ['refer,obese,cubic,nicer,swoon', 'ccosu,fbweb,creoe,nirer,seion'],
//   ['musty,woozy,raspy,rover,ramen', 'mesry,zorwp,resyy,vnrao,tamuo'],
//   ['quite,knoll,chill,canoe,cheat', 'qoato,keenl,ihcla,clluh,cenit'],
//   ['shoot,serve,pride,lathe,plane', 'rport,heoie,psvda,eetsl,hnale'],
//   ['brace,shaft,think,solar,slack', 'laali,ssrfa,thenk,srbko,hctca'],
//   ['dumpy,cynic,rapid,aging,drive', 'mudri,cynyc,papni,eviir,dgdga'],
//   ['micro,taffy,sever,yearn,smirk', 'mimit,oyffa,sreve,eyarn,kcrrs'],
//   ['tatty,bagel,gooey,fetal,aping', 'tytpe,fagel,goiaa,byaeg,ttonl'],
//   ['shift,gauge,eagle,wrath,throb', 'ahtrg,gsutt,eawle,gfrih,eoahb'],
//   ['peach,every,limbo,ebony,steer', 'ibvyh,eaere,bpmee,rlonc,stoye'],
//   ['scuba,radar,randy,fever,carat', 'arrat,radsr,uaaey,frvdc,cbena'],
//   ['bland,shied,bobby,matey,latch', 'tbamo,syiee,tdbly,nabdh,cablh'],
//   ['swarm,cream,satin,polka,snout', 'srawm,traem,nacss,optka,inuol'],
//   ['risky,purge,booby,synod,charm', 'boeky,hurns,biyry,oogsa,cpdrm'],
//   ['hurry,edict,scamp,might,focus', 'huoms,etgus,ycarf,miihd,prcct'],
//   ['jazzy,catch,fibre,woven,drawn', 'zatja,cazhc,frovd,wbren,eiywn'],
//   ['ripen,cabal,abyss,fifth,tooth', 'biaen,ilyaa,prbhf,fcsts,ootth'],
//   ['humor,quoth,myrrh,berth,crave', 'hocmy,quuah,orrrh,rtbev,mrthe'],
//   ['rearm,great,setup,cleft,erect', 'crtsm,urltc,reagp,reeft,eeeta'],
//   ['perch,steep,hymen,posit,clasp', 'peept,shrsn,oymep,ahsic,tlpec'],
//   ['eying,retch,shrew,safer,shook', 'iyegn,retch,owkeh,sfaeo,hsrsr'],
//   ['brook,drown,sower,kinky,booze', 'benok,orbsw,wonre,ikoky,odozr'],
//   ['ennui,cargo,palsy,stake,sheen', 'einan,rscgo,sklpt,eyuas,aheen'],
//   ['begat,carve,dizzy,pleat,cheap', 'brgzz,clevy,tatae,paead,chpie'],
//   ['greed,boozy,soapy,leash,vying', 'enggl,bozoy,soapi,dsaev,hyyre'],
//   ['lyric,slide,snowy,scary,chain', 'ylric,swyin,secly,ncahi,orads'],
//   ['amuse,lanky,junta,pause,talon', 'lmeeu,aasty,ounkl,pauns,atajn'],
//   ['gully,riper,bough,trite,wedge', 'giley,rupei,buogt,edrht,wgrel'],
//   ['roach,scree,morph,whirl,sweat', 'hoocr,rcawh,pasme,ehtrl,sweri'],
//   ['kebab,curve,plume,swung,dingo', 'aedkb,cuevr,osunu,lwemn,biggp'],
//   ['salsa,salon,suave,croak,demon', 'srkoa,ssaoe,aulve,nasal,onmdc'],
//   ['mogul,wacky,rough,whiny,mafia', 'moiyo,awkcy,nligh,hwuru,mafga'],
//   ['amaze,frill,grind,cinch,crony', 'ailne,cnroa,nimgd,cizch,frlry'],
//   ['amble,equip,index,voter,felon', 'aeele,mfnip,ixrln,ovted,qbeou'],
//   ['buggy,whine,slush,panel,wrung', 'bulgy,sheui,phuwl,senag,nrnwg'],
//   ['scowl,bylaw,amend,thorn,scour', 'aoowl,snuew,smayc,thnro,bdclr'],
//   ['bluff,smite,house,nurse,unset', 'nemrf,sustu,huuie,tefse,obsln'],
//   ['cutie,smith,masse,caput,condo', 'cotii,scemp,tocse,mahun,sutda'],
//   ['ankle,weigh,amity,marry,chase', 'lgaaa,teinm,emrwy,hkihy,crase'],
//   ['modal,psalm,swami,piney,gnash', 'ngadl,amaml,sapsn,piiey,omwsh'],
//   ['drake,cease,macho,slunk,radio', 'deeka,ceonr,racho,dulsk,misaa'],
//   ['clamp,piety,bowel,furor,chose', 'ciboh,wleco,ampeo,furyr,tplse'],
//   ['fatty,agora,spike,cairn,cruel', 'patel,acarc,rfkit,goisn,aruey'],
//   ['sushi,spasm,snoop,amber,erupt', 'usstb,somsa,onspp,umipr,eraeh'],
//   ['flock,gorge,liege,chief,baggy', 'ogfck,ifrge,ggale,bhieo,ceylg'],
//   ['cleat,needy,light,grout,briar', 'ctral,ueedt,biggy,hrrnt,leaio'],
//   ['cacao,snarl,fried,miser,moral', 'lamfo,rosrc,almed,ciaes,inrar'],
//   ['canny,abbot,chasm,scorn,sorry', 'csbny,cbnor,srosr,caamn,aothy'],
//   ['dimly,pesto,bused,lucid,whack', 'timku,peods,ausec,wyhid,lcbdl'],
//   ['torus,peril,print,globe,bless', 'nopul,resli,erite,gsobp,bstlr'],
//   ['music,nerve,straw,after,wiser', 'mwarc,aerfr,wtrsu,nviei,stsee'],
//   ['vowel,field,iliac,ladle,wheel', 'lohel,eelld,aliie,lwdef,awciv'],
//   ['chick,glint,buxom,slime,elder', 'chbgm,clunt,iiese,orikx,mldel'],
//   ['raven,beard,booty,staff,hutch', 'bavty,rcard,futtn,soahb,foeeh'],
//   ['filly,quest,payer,solid,livid', 'iflli,qudse,raotp,lysve,liiyd'],
//   ['novel,nasal,befit,missy,gourd', 'novei,nfsrs,dsalt,imley,uogab'],
//   ['rivet,bloat,kiosk,comic,pique', 'rivsl,otbat,oikei,qpeic,okcum'],
//   ['shalt,dodge,paddy,thigh,patch', 'ihtdt,docgy,hhlde,pasgh,taadp'],
//   ['drain,apnea,biddy,cluck,lipid', 'anpir,auldd,byedi,cnpik,lcaid'],
//   ['dingy,baton,imply,antic,curry', 'nudgt,bayol,pminy,acrin,yitrc'],
//   ['groom,final,brawl,borax,dance', 'rgboa,ainaa,lrlwb,oermc,dfnxo'],
//   ['acorn,meaty,wrack,shake,wimpy', 'kwamn,meyta,ycora,hsake,cirpw'],
//   ['grace,knelt,ditch,sixth,mambo', 'grati,nkdxt,eeohc,bilch,mamst'],
//   ['spice,stunk,genre,adopt,flame', 'mefap,stutp,aenre,godkn,ilcse'],
//   ['fanny,tenor,actor,renal,aunty', 'nnnna,toneu,yytrr,oefal,traac'],
//   ['marsh,flush,sauna,llama,stink', 'htrss,fnuhm,laasa,sluia,namlk'],
//   ['geeky,valor,crawl,honor,patsy', 'gyekw,acpor,arvyl,htnsa,lrooe'],
//   ['joust,drink,gusto,shaky,braid', 'kdsat,orirk,huayo,ugsjt,bnsid'],
//   ['cabin,lunge,shard,spent,thump', 'crnpn,hunge,uldaa,siebm,phstt'],
//   ['drift,still,whale,pushy,pearl', 'rdlyh,spiwl,ltaiu,peshf,trael'],
//   ['silly,guise,prior,drape,mushy', 'eiihy,pulrs,asuor,rdpge,misly'],
//   ['leach,cello,dummy,array,quail', 'lalch,oeauc,dummr,lyyer,alqia'],
//   ['mamma,witch,swamp,cater,plant', 'mcmri,tawaa,swamp,naplm,tehct'],
//   ['dirty,chide,broad,surly,bluer', 'dhlyt,diace,broie,rlrry,buuds'],
//   ['chalk,lucky,parka,shunt,mossy', 'uhknk,cclss,oaraa,khult,spymy'],
//   ['cumin,world,leper,three,disco', 'luein,chlrd,cepre,tosmo,dirwe'],
//   ['unlit,floss,clued,creek,spawn', 'snkic,lwaus,tfred,euecl,spoln'],
//   ['cried,fixer,avail,toast,tabby', 'crvtr,iaxed,sibfo,tlaat,eibay'],
//   ['privy,quark,pagan,write,spore', 'erviy,uqrrp,kagas,paito,nwerp'],
//   ['octet,rinse,since,leggy,power', 'icnrt,sotrp,snice,yeggl,ewoee'],
//   ['paint,medic,gross,equal,reign', 'oaius,ieemq,erpst,dcnal,rging'],
//   ['shale,going,shrug,civic,tasty', 'sgyle,uosni,shcgh,riagt,tvica'],
//   ['hunky,motor,false,break,blond', 'hrbry,mkoou,fdles,lkeao,nbtna'],
//   ['jewel,shyly,stare,excel,libel', 'jxhee,rwysl,lease,teiey,lcbll'],
//   ['freed,alley,shuck,lymph,sting', 'ygehd,nlmhp,seukc,lflye,stiar'],
//   ['arbor,totem,panic,organ,funky', 'mbron,aotea,ntpkc,frgun,oariy'],
//   ['brash,gaudy,jerky,humus,stoop', 'bdeoh,gkurs,sayar,humuy,jpsot'],
//   ['shirt,haven,taper,donut,rocky', 'erohh,taevn,uapsr,dintt,rkyoc'],
//   ['racer,filth,minor,wrong,lurid', 'raiur,nogtr,mcoid,whnfl,lerir'],
//   ['bezel,bunch,penal,tenth,local', 'hobnl,zunce,leeap,chnab,lettl'],
//   ['debug,theft,manly,above,gonad', 'debbn,vehyl,gagtf,auoto,menad'],
//   ['baron,midst,trout,chair,furry', 'iaasd,hinot,crofr,tmrbr,uutry'],
//   ['scene,brine,bacon,stalk,blaze', 'csens,bnire,aocat,enale,zlbbk'],
//   ['hoist,freak,limit,flesh,moult', 'ooist,fehls,ltmii,umrke,lhfat'],
//   ['blare,glyph,cadet,event,blame', 'yepee,hlbag,aadbt,rvlne,elcmt'],
//   ['rhyme,defer,skill,smell,penny', 'eryme,dnsrh,lmesl,fkipl,leney'],
//   ['poise,visor,party,speck,smelt', 'pasis,ciper,pomky,esovt,srelt'],
//   ['joker,audit,dicey,friar,untie', 'ickar,uatdr,iioey,fniet,urdje'],
//   ['opera,petty,cover,torch,plump', 'hpare,petco,eylcu,morto,pvrtp'],
//   ['bribe,pygmy,picky,vocal,sleep', 'lpeba,pgycy,oimky,vpleb,scier'],
//   ['datum,abuse,forum,quash,genie', 'dtaum,sbmae,eersu,quhua,nogif'],
//   ['prose,proxy,eclat,layer,worst', 'prece,rpryy,oslew,laxar,toots'],
//   ['cloud,heavy,earth,dolly,scoop', 'rucld,eeavy,hacsl,dohop,toloy'],
//   ['roomy,drier,zonal,bravo,swing', 'roolw,nraer,vasim,boozr,nyidg'],
//   ['twixt,vicar,lunar,daily,dusty', 'iytat,aicvd,uunar,rxiyl,dltsw'],
//   ['goofy,annex,doing,fizzy,piece', 'fooey,apyxe,zoeng,gizdn,nciif'],
//   ['caste,depot,teeth,slurp,louse', 'cdset,aolet,eteru,slhte,pousp'],
//   ['heady,mower,piper,chunk,ounce', 'hwaur,koecy,unper,enpim,odhce'],
//   ['belie,sheet,these,beget,bound', 'bhlbe,tegts,tebde,iheee,eouns'],
//   ['gnome,broom,icing,below,speed', 'ngenl,rbdoc,imimg,beeop,sweoo'],
//   ['fritz,slick,parse,endow,basin', 'bries,slica,ikrzo,tsnew,fanpd'],
//   ['trial,merge,verso,clock,inane', 'ereeo,marrt,cigsa,vllkc,inone'],
//   ['incur,lapel,vista,berry,anime', 'nrrsn,lmtrl,vyupa,beeci,aiiae'],
//   ['spite,prime,spool,stomp,stoic', 'sopte,itscl,spmte,sooop,irpim'],
//   ['brass,sixty,sweep,tower,sonic', 'sribe,sitxy,wssew,nopec,sotar'],
//   ['sound,skulk,shout,revue,coral', 'horns,lcusk,dseul,uovue,karot'],
//   ['girth,aloof,lumen,cramp,login', 'orimh,alcpl,futei,onamo,lggnr'],
//   ['forgo,agape,rower,bingo,happy', 'foogn,girop,araer,bgoap,hwpey'],
//   ['cavil,foist,grade,axion,sneak', 'aaeil,ofisr,atons,cxian,edvgk'],
//   ['dress,shoal,spear,elfin,weedy', 'dwees,sroae,slsih,epfay,rdlen'],
//   ['shady,choir,alone,brief,aglow', 'dlnsy,cfoir,gabae,oriwh,lahoe'],
//   ['fishy,lemur,churn,ionic,nosey', 'foncy,uomch,hrlrn,ieseu,nisiy'],
//   ['rarer,cedar,plier,swill,fifty', 'rswdi,rieac,plrli,arele,frfty'],
//   ['inlet,diner,graph,digit,exult', 'inhet,lpngr,dtail,gtexi,eiudr'],
//   ['aider,faint,flout,acute,cower', 'witlc,faiod,uetto,arfue,cnaer'],
//   ['curvy,ficus,onion,wafer,gloss', 'ssros,oecuu,fnirn,wfaio,glvcy'],
//   ['click,grill,smile,guest,match', 'icurg,gchll,mscte,kiesl,matli'],
//   ['crept,sully,skimp,tenet,bosom', 'ctsnr,sikmy,elulp,oepot,bestm'],
//   ['trump,flask,devil,kayak,cough', 'srufa,muatd,kveil,kaypc,kgloh'],
//   ['visit,billy,alarm,issue,geese', 'vilst,alesy,bierm,esiul,egisa'],
//   ['grave,frank,knife,quack,afire', 'afgve,rrakr,nkief,quifn,acake'],
//   ['draft,diode,blood,revel,cloth', 'deafd,tiodr,odbll,eetro,chovl'],
//   ['wreak,stall,dutch,prize,truth', 'wheit,tshdl,lukcr,teazr,pruta'],
//   ['stung,ascot,forte,burst,wound', 'ecgnu,ofttt,saros,wunst,bourd'],
//   ['logic,minus,vaunt,betel,goner', 'lltgu,einub,vocnt,srgmo,ianee'],
//   ['cross,topaz,grain,fauna,booth', 'arnus,tioan,gocoz,fhsoa,bprta'],
//   ['rogue,havoc,nomad,mason,alike', 'uonre,haoom,socid,manvg,keaal'],
//   ['twang,spiky,grief,email,rouse', 'uragn,psiie,greyf,isakl,wotme'],
//   ['gloom,sleek,shade,flirt,idyll', 'gsodd,lheee,sltok,lliia,rmyfl'],
//   ['aback,clean,crush,react,thyme', 'ebmct,cyrau,censh,eacak,thlar'],
//   ['spoon,verge,dying,axial,camel', 'epven,ooxya,dgina,ariem,cglsl'],
//   ['willy,stump,hunch,abort,ultra', 'wirly,hauca,nuhms,tbtto,ulrlp'],
//   ['harsh,route,omega,unwed,strip', 'euase,roith,dmhgr,atewo,snrup'],
//   ['fruit,stock,zebra,toddy,daunt', 'fautd,buodk,zrsey,todta,crtni'],
//   ['imbue,fight,mauve,savor,fugue', 'vmure,fegat,ufmii,shvuu,aogbe'],
//   ['frond,judge,drawl,augur,broth', 'fdwur,jurgh,rdgoo,auand,brlte'],
//   ['modem,covet,watch,dryly,mouth', 'mmeuo,avodt,cctwt,dryoy,mlehh'],
//   ['tempo,creed,sense,porch,fraud', 'sedpp,heree,tcnrd,oorec,fsaum'],
//   ['baker,tonga,shark,macro,idiot', 'ookca,nbtga,shrrm,kdera,iaito'],
//   ['craft,shawl,brood,mayor,bliss', 'oohft,malwl,bsrrd,syaco,bairs'],
//   ['expel,puree,manic,mangy,razor', 'eaezr,pyerp,mxing,mancu,laeor'],
//   ['regal,unfit,unfed,otter,batty', 'feeul,arrtt,atfgd,oityn,butne'],
//   ['boost,blown,wring,pluck,comma', 'oorst,aolln,moinp,gwumk,cbwcb'],
//   ['salty,graze,worth,crone,bongo', 'gooce,argth,wlrze,trany,bonso'],
//   ['stack,ovine,slimy,allot,amiss', 'ytakc,salmi,slins,ailos,vmeto'],
//   ['seize,crane,unify,ethos,bevel', 'neizu,craho,esivy,elnee,esfbt'],
//   ['lasso,sloop,lousy,bulky,gouge', 'losyl,sloos,oaupg,ubles,oguyk'],
//   ['wryly,torso,chard,snipe,shrub', 'ryrlh,nowso,hybrd,rtips,ecsua'],
//   ['noisy,white,crumb,crier,liner', 'eornt,lriyn,crcib,uimeh,wiser'],
//   ['laugh,scram,seven,apart,unmet', 'aaagh,sertm,scnev,leuna,mrupt'],
//   ['beech,chafe,class,prowl,swine', 'speln,flacs,chase,eriwc,bwohe'],
//   ['widow,impel,latte,atone,slice', 'oedwt,imsli,lotei,awant,pelce'],
//   ['ensue,rumor,found,hence,pesky', 'snoye,ruusd,fcmnr,penok,heeeu'],
//   ['inert,tweet,groan,stiff,cocoa', 'ootrt,ewfrt,aeigc,scief,notna'],
//   ['tuber,relay,stark,crepe,twist', 'eucer,sklaa,wtyee,bptrr,tsirt'],
//   ['money,fully,water,mural,plain', 'ltnwl,fmyly,eroei,upaam,ularn'],
//   ['tried,bison,sally,quiet,broil', 'iroei,udson,rqtly,abtil,bsiel'],
//   ['papal,gusty,swath,eager,upper', 'ghutp,wpste,sguaa,yaper,alper'],
//   ['etude,hippy,stint,vapor,tying', 'pisht,dtppy,uogni,vaetr,eytni'],
//   ['virus,smash,swore,slash,elite', 'vilua,wmsss,ssero,heath,iresl'],
//   ['midge,clone,ranch,inlay,putty', 'midgl,iehar,eanyo,cnynl,tutpc'],
//   ['stool,humph,ferry,plate,skirt', 'teofr,puhlm,oelrr,hpast,skiyt'],
//   ['truer,utter,thong,moody,being', 'eyoed,ntttb,tgeng,muorr,roiuh'],
//   ['dread,rainy,yacht,meant,brawn', 'ddnar,yhity,raman,cwart,bnaee'],
//   ['while,fresh,piggy,right,input', 'teifh,luthh,piygg,rigsw,nipre'],
//   ['check,puffy,rayon,dwarf,tango', 'chkae,fgfpr,raytw,fncyd,oanuo'],
//   ['wagon,juicy,gipsy,swept,vouch', 'hogau,juews,gipoy,ycipv,tsncw'],
//   ['flair,lowly,kneel,thing,fault', 'llafr,etnut,kleln,ohiwg,ialfy'],
//   ['annul,night,vigil,glean,tight', 'aneul,ianht,litnt,gvnig,ggihl'],
//   ['waltz,relic,surge,thank,crisp', 'lapth,ctwis,sureg,ezank,rircl'],
//   ['itchy,knock,rumba,plaid,spark', 'itihb,knkcl,pupyr,mkacs,draao'],
//   ['villa,flint,using,strap,quell', 'ailsa,tgqnu,nlsul,ifrvp,itell'],
//   ['stilt,query,raise,vixen,femur', 'etert,ausiy,lqiem,frxin,vseur'],
//   ['usage,sleet,fluke,erode,spilt', 'usele,igdal,ftlke,prsee,oesut'],
//   ['vegan,stair,truce,grate,pupil', 'vnrre,tstia,aruae,ggctp,pieul'],
//   ['sooty,older,rider,crack,ovoid', 'icyro,oldkt,airre,cdroe,ovosd'],
//   ['lunch,radii,cache,craze,waxen', 'lwneh,cadia,einhc,rezac,uaxrc'],
//   ['share,slosh,boxer,butte,taunt', 'bonrt,hlous,shxer,btuta,tesae'],
//   ['foyer,umbra,daddy,belle,brute', 'edbfl,uayra,omddu,brree,beytl'],
//   ['worry,taint,juror,spoke,minim', 'moasy,trnir,jntpi,rooke,mruiw'],
//   ['jumpy,faith,deter,outer,brink', 'ujtpo,krbth,eetdr,yumen,iairf'],
//   ['flank,madly,shave,junto,testy', 'lfany,taldy,ujavs,hsntt,oeemk'],
//   ['gripe,china,triad,album,shore', 'urmra,ihcoe,triae,slbgi,ahnpd'],
//   ['gaffe,blast,inter,fewer,clack', 'lrfrt,fease,ineea,btclf,wgack'],
//   ['liken,diver,women,sword,threw', 'viowh,edler,wmoes,nwkri,tnrde'],
//   ['cling,paste,again,steak,beret', 'asine,aalts,pkian,etecg,btrge'],
//   ['conic,melee,duchy,pitch,tread', 'tohpm,celed,eucna,ircct,hieyd'],
//   ['ozone,navel,abate,wager,slyly', 'leyby,naevg,anatz,walel,srooe'],
//   ['corny,scrum,flunk,extol,demur', 'rornx,lecue,flukn,cydrs,tmmuo'],
//   ['hazel,chili,axiom,rebar,easel', 'iezeb,cheih,oelam,rilaa,xrsal'],
//   ['rodeo,bigot,fetus,hoard,tacit', 'uodtf,bsgto,oeari,htadr,etcio'],
//   ['noose,width,leaky,towel,south', 'nukol,tidya,lehot,wswee,hoots'],
//   ['ethic,amply,sharp,shine,ratty', 'attic,empsy,thhnp,laeri,yashr'],
//   ['elide,ninja,elope,phone,tough', 'opiuh,einjl,naeep,letne,oodgh'],
//   ['major,satyr,could,utile,sumac', 'mijur,uttyr,ecoad,saalc,usmlo'],
//   ['oddly,spout,sulky,flack,bloom', 'addct,skmuy,yllks,flolp,ouboo'],
//   ['jaunt,tulle,sunny,elbow,realm', 'nuajb,eunlt,selnl,rytow,eualm'],
//   ['paper,abbey,begin,beset,clout', 'pcuny,asblr,iegbe,btbee,aeopt'],
//   ['gaily,later,moose,crimp,stout', 'ptius,altic,mooyt,rremg,seola'],
//   ['nerdy,scarf,atoll,valid,chest', 'ocril,eharf,dtnly,lavda,ecsst'],
//   ['fluid,tweak,hedge,aloud,trope', 'kpure,eweaf,lddgt,dhota,uiole'],
//   ['guilt,angle,entry,cobra,hinge', 'naior,uggle,eerty,blcta,nihgn'],
//   ['lorry,vigor,blush,waver,biome', 'bobrr,ivgoy,lluse,movir,reawh'],
//   ['froth,hotel,algae,troop,patty', 'ttota,heaep,hlgto,oytol,pafrr'],
//   ['decor,slept,comet,gaunt,niche', 'edcoo,tehps,crmut,naeit,gncel'],
//   ['azure,dandy,linen,sweet,resin', 'nzuya,deeer,lirnn,tedws,nesia'],
//   ['payee,waste,stein,decoy,coyly', 'yapye,tcewe,sesyn,dtaoi,cleoy'],
//   ['joint,point,vague,fatal,gruff', 'tugge,toirj,vaift,uapal,nnoff'],
//   ['outdo,frail,evict,siren,halve', 'adiuo,erlna,ivtcr,setfi,holve'],
//   ['phase,guile,preen,plait,badly', 'aahsl,enile,paegu,piplb,trdey'],
//   ['crass,welch,vogue,mourn,color', 'oelsw,srach,vrgun,ocuce,rolmo'],
//   ['image,tripe,borne,cable,abode', 'ambgl,arbrb,aepne,cieee,tiodo'],
//   ['dough,timid,sewer,unzip,growl', 'gwumh,oigid,wrope,ulzie,drtsn'],
//   ['stuff,third,habit,ghoul,plunk', 'ltdko,uhuau,nrbit,ghftl,psihf'],
//   ['badge,burnt,squad,brisk,bonus', 'baoue,bbtur,iqgad,nrsks,udbns'],
//   ['sloth,beefy,bunny,elude,scant', 'tlyed,betso,buncn,ulehe,fnays'],
//   ['quart,patio,newer,speak,sight', 'qiaat,srruo,aeeet,phwnk,isgpt'],
//   ['tiara,wispy,wordy,verve,harpy', 'rwero,wrppy,iatra,vedva,hyisy'],
//   ['caulk,lever,agile,crest,dodgy', 'eailt,geycr,alule,dsork,decgv'],
//   ['grime,donor,mecca,risen,quasi', 'emirg,msiin,decea,roscr,quaon'],
//   ['plaza,maxim,lumpy,ester,guppy', 'ieaza,tmxpe,lrapy,mgmlu,spupy'],
//   ['tidal,stood,depth,spend,adapt', 'etddl,doota,sdpih,tatne,adpps'],
//   ['spill,harry,mealy,sheer,segue', 'mesll,eayhr,seely,irepu,sagrh'],
//   ['pulse,primo,ideal,boule,daisy', 'ppubi,uremo,sdeil,sally,doaie'],
//   ['grasp,cause,karma,coach,cliff', 'hrasa,cakcm,uarep,clfcg,sofai'],
//   ['windy,spoof,thief,spoil,lying', 'oinon,fidhs,soeif,tpwpl,lyiyg'],
//   ['frisk,loopy,fudge,tutor,waist', 'duitu,yoorl,frfga,sksop,weitt'],
//   ['optic,dally,least,arena,edify', 'fpeid,dylla,teaal,iytns,ecaor'],
//   ['nanny,ovary,alpha,rebel,flume', 'yapfb,oamrn,vlnhr,aeyel,nleau'],
//   ['press,early,gavel,media,aside', 'paiee,erala,damel,vsdey,rsigs'],
//   ['robot,other,singe,tunic,elect', 'tehet,erbor,stngi,icneu,oloct'],
//   ['koala,wench,green,cigar,snare', 'aeack,worcr,gnnan,lgiar,seehe'],
//   ['delta,gauze,blurt,shank,dully', 'duutg,aabze,ullyk,hsalt,delnr'],
//   ['twirl,super,throw,facet,elate', 'twlfi,statr,chore,rptee,wlaue'],
//   ['abase,anger,droit,feign,mount', 'aeare,gnube,isodf,triam,nognt'],
//   ['teach,poker,under,amass,pried', 'raeih,pneet,rodka,aerss,pucmd'],
//   ['steel,drank,tacky,magic,stove', 'dtteo,scank,yirkt,cavam,selge'],
//   ['maize,valve,moron,wight,belch', 'mewle,bazva,iorno,imhgt,velhc'],
//   ['crump,awful,ditty,exile,viral', 'ldimi,vufwc,rpety,txuie,alral'],
//   ['dozen,exist,suite,loyal,adage', 'igzel,eaiul,ssdet,noyet,adxoa'],
//   ['front,ovate,polar,plied,spree', 'fronr,lavta,seoer,ilpep,pdteo'],
//   ['guess,rabbi,irate,bully,cress', 'liyss,sabbt,ureie,bscge,lraru'],
//   ['spare,shear,afoul,round,jumbo', 'mpuol,ohead,afoje,uranr,ursbs'],
//   ['rupee,sandy,tamer,relax,decry', 'muydd,taney,sarrx,relcr,eeaep'],
//   ['reach,banjo,hello,eking,bicep', 'bpnch,eanki,hboil,ejoag,rlcee'],
//   ['baler,rhino,scrub,mocha,stave', 'burha,lerno,vciab,soahr,mtcse'],
//   ['pilot,crick,sport,child,kneed', 'slert,ioidr,ppokt,chcie,knldc'],
//   ['deign,foray,eaten,trend,semen', 'iedgn,eneay,emete,trnsd,nrafo'],
//   ['goose,shame,perky,audio,giver', 'moose,iergh,gervy,aduie,pskoa'],
//   ['grass,gruel,ashen,birch,lingo', 'glcer,nrnsr,aehsg,bisah,lougi'],
//   ['haunt,foggy,rehab,riser,prude', 'haunr,fbepr,rsrao,yueeh,gtidg'],
//   ['chart,skate,plush,coast,noise', 'oorat,sphte,klcsa,ucasi,ehtsn'],
//   ['merit,wrest,niece,holly,snack', 'ilhin,wcese,nmtre,roela,ktycs'],
//   ['adult,human,drill,turbo,angry', 'luula,ddgob,hnila,turna,trmry'],
//   ['moldy,cheek,where,shelf,venue', 'coryd,mkhfh,weele,sheee,veunl'],
//   ['apron,forth,spiny,crash,opine', 'anrno,eosta,spipo,rchrp,yhinf'],
//   ['quake,apple,north,farce,ready', 'klaqe,adruf,ncrth,eepoe,aarpy'],
//   ['fiend,theta,flyer,storm,bleep', 'rpefs,thelb,ntyee,dtmfo,aleri'],
//   ['blurb,tryst,tease,plank,debut', 'tetbb,trylu,tnade,psaeu,slrkb'],
//   ['quill,stray,woody,inept,saute', 'suioa,woray,sltdi,yteut,qlpne'],
//   ['medal,teary,diary,wheat,heron', 'reaal,toamn,riddt,hwhay,eerey'],
//   ['loath,denim,bride,fungi,greet', 'eratg,eenim,ioedl,frnhb,tuidg'],
//   ['voice,admit,upset,start,sheep', 'siict,admor,tetee,vsatu,shppe'],
//   ['orbit,olden,alien,ruder,ahead', 'nrdit,ehueo,nleaa,rdbor,eliad'],
//   ['froze,rival,delay,savvy,blimp', 'fpyye,aivav,velaz,lrldo,bsmir'],
//   ['quirk,offal,decal,extra,tapir', 'kaiaq,xffrl,lecrd,toeau,tarip'],
//   ['rugby,bilge,asset,surer,split', 'bygbu,riege,sraet,sruls,pslti'],
//   ['enact,penne,folio,spurn,await', 'csaee,pennt,aolio,nnwap,rufti'],
//   ['tawny,adore,hitch,guava,trade', 'tdwad,ayorg,rceiu,ehnva,thaat'],
//   ['splat,cagey,widen,peace,float', 'ftado,aagey,weacn,pecei,sltlp'],
//   ['feral,mirth,bloke,level,saucy', 'flmeh,rlrtl,beeka,ioale,svucy'],
//   ['comfy,lower,urine,khaki,dogma', 'carfk,koewm,unire,lahyi,dgomo'],
//   ['abide,fetid,queer,those,honey', 'ooihe,nhtdi,yuees,tebre,dafeq'],
//   ['lager,creep,newly,whose,swish', 'lahpi,cyeee,slher,sgose,nwrww'],
//   ['clang,parer,hefty,nylon,crude', 'clneg,panrd,techy,ayuor,felrn'],
//   ['curse,snake,shape,along,minty', 'narse,sanki,sntoe,ugpcl,mehay'],
//   ['goody,fancy,munch,short,fiber', 'gyydo,rhtco,mciuf,saofn,hnber'],
//   ['tribe,viper,stash,curio,worse', 'hbore,vaprc,stiut,rseio,sirwe'],
//   ['debar,leech,squat,infer,stick', 'sebtl,rtehc,dquie,airef,sanck'],
//   ['finer,fluff,hardy,yeast,melon', 'lisfr,ffdea,hayur,yefne,mtlno'],
//   ['allay,offer,basil,brush,table', 'flbay,ibaeh,fasol,lrsur,atlbe'],
//   ['filet,maker,neigh,gumbo,drunk', 'neiit,mgkbr,ngleo,auueh,drmfk'],
//   ['crook,crust,deuce,clove,swoop', 'cukoo,cerpw,devlr,ccous,etoos'],
//   ['titan,never,avoid,lemon,gulch', 'tutmn,nonev,arlhe,odaev,gilci'],
//   ['board,skunk,slope,owing,title', 'laord,onult,snope,siwki,kgtbe'],
//   ['known,punch,skull,aroma,retro', 'nulrk,poack,shnto,arumn,welro'],
//   ['tonal,rigid,roast,assay,awoke', 'rlaao,oagsd,triit,nosaa,ywske'],
//   ['piano,awake,welsh,boney,exalt', 'lixao,anekb,hepsw,eowet,aanly'],
//   ['bossy,repel,steal,loser,force', 'srscy,eoper,betal,lsoeo,felsr'],
//   ['icily,clown,scrap,legal,cycle', 'sreoy,cllgl,iccac,nawel,pycli'],
//   ['artsy,giddy,buddy,queue,wharf', 'drtyy,bqfry,gueas,iudwe,uhadd'],
//   ['mania,debit,kitty,about,flier', 'mitfa,detab,ueati,tbokn,ilyir'],
//   ['coven,boast,sadly,shire,smock', 'rovne,aosis,abdhy,tlscs,emock'],
//   ['undid,golly,undue,yield,truss', 'oeley,nudud,ugdui,sinld,trlys'],
//   ['girly,creak,glaze,pivot,erase', 'ktazy,creag,elrle,eavsi,griop'],
//   ['eight,clear,snaky,sober,hovel', 'alevs,rlgar,theky,soeec,nohbi'],
//   ['alive,canal,wider,eerie,among', 'reile,inaiv,wadlr,egaco,amene'],
//   ['trail,admin,bring,store,cabby', 'crlia,airdi,synng,btbme,taobr'],
//   ['crock,curly,decay,avian,dwelt', 'yeock,rtcec,crday,alidn,awlvu'],
//   ['locus,hatch,saner,sniff,oxide', 'aocsu,itace,nlshx,sndff,orhie'],
//   ['vinyl,queen,toxin,ridge,sauce', 'viuye,rnsln,ioxtn,qeuge,ecdai'],
//   ['spine,grimy,rebus,maybe,ghost', 'ypgse,irmis,geten,mayou,rhbsb'],
//   ['macaw,pinky,blank,wrote,sassy', 'kaans,pisyy,blwam,asote,ncrwk'],
//   ['slate,notch,ought,envoy,proof', 'ahsth,nooce,ytglu,vnero,pootf'],
//   ['slang,whoop,enema,scoff,scold', 'scdno,moohp,enlws,aogff,slcea'],
//   ['crazy,first,tardy,large,soggy', 'cgtly,yiest,agrag,zdrar,soryf'],
//   ['jolly,lover,trait,blade,motto', 'jrall,aevoo,tdlti,bylre,totmo'],
//   ['tangy,strut,molar,horse,salad', 'tnaod,tsaut,mgarr,slrhe,saoly'],
//   ['irony,crowd,foamy,opium,remit', 'ireop,cmnim,aofry,oyiud,tomwr'],
//   ['month,alloy,cyber,scion,rigor', 'oonts,laemn,ryblc,hrioy,crgoi'],
//   ['mover,lance,shove,naval,salvo', 'vnvhr,vvoca,lelae,nemas,saolo'],
//   ['study,outgo,often,flick,toxic', 'sutoy,dnift,ogoxu,kltcf,toeic'],
//   ['bathe,bible,jelly,fairy,anode', 'jaiay,dtlbe,bflli,ehyre,anobe'],
//   ['hobby,carol,arson,puppy,trawl', 'blwhy,calro,rasan,pppuy,toobr'],
//   ['broke,attic,prank,flail,briny', 'nrrte,ikflb,prayk,tiail,coabn'],
//   ['sling,hairy,fleet,taste,loamy', 'lliym,hrian,osaee,tsatt,lfegy'],
//   ['silky,aptly,basis,probe,lofty', 'fyyal,kpbli,baoil,ptote,sssry'],
//   ['pulpy,meter,pouch,purse,gamer', 'uptgc,melre,pouyh,mursr,pepae'],
//   ['repay,began,empty,burly,sheik', 'ygtay,yseun,emlpr,iarpb,ehebk'],
//   ['duvet,exact,ardor,smoky,usher', 'otvht,esaru,areok,xmdru,ysedc'],
//   ['manga,spunk,stuck,gassy,mucus', 'uauns,aumgs,stucc,massy,gnkpk'],
//   ['cider,dream,hippo,lupus,urban', 'ldieh,uouam,rbpar,cupes,dripn'],
//   ['adorn,weary,helix,colon,guide', 'awonc,dearg,ulexi,nolor,yhedi'],
//   ['close,build,scone,dairy,naive', 'vcase,diieb,nlorl,douny,saice'],
//   ['twice,coupe,leave,shell,steam', 'thivl,ceale,poace,swete,slmue'],
//   ['stamp,award,grunt,catty,slung', 'staas,uwayr,tdagl,cmgtr,ptunn'],
//   ['birth,olive,dirge,spurt,swear', 'tirbw,rlevd,eigra,tpurs,shieo'],
//   ['smear,snort,chime,hotly,aphid', 'eoser,simrt,hhiha,mldoy,apcnt'],
//   ['union,savoy,snore,venom,fling', 'ueson,iovam,irfnn,vgnoy,olsne'],
//   ['whisk,valet,spell,terse,slink', 'whiev,kapse,llssl,etiet,slrnk'],
//   ['annoy,mercy,spicy,heath,dealt', 'ipery,hsoca,enacy,hnadm,teylt'],
//   ['snail,stage,chess,grape,afoot', 'saeco,stgae,ihags,srnto,afelp'],
//   ['score,learn,derby,groin,trunk', 'seorc,lnudt,rrbri,geoye,nrank'],
//   ['drove,tense,golem,merry,inbox', 'dervb,mnesr,loget,xeoyr,ineom'],
//   ['squib,treat,cacti,adept,purer', 'pttii,pdtaq,caceb,aresu,tuerr'],
//   ['space,alert,viola,order,pinch', 'ipnae,clctr,riolp,orhev,asaed'],
//   ['dilly,glade,avert,prism,value', 'tglrv,imive,ayeld,praul,dalse'],
//   ['today,bleat,horde,rebut,truly', 'eorul,uyeht,aoddr,etbbt,trayl'],
//   ['inner,rural,mouse,batch,stony', 'crner,lsnhr,motse,bouia,unaty'],
//   ['leafy,dowel,teddy,stoke,total', 'ksfao,tywol,doday,etele,tetdl'],
//   ['roger,krill,gleam,vivid,stand', 'rnllr,vsiea,ggelm,ddkii,rtaov'],
//   ['truck,swell,climb,movie,askew', 'tolck,silek,auimw,ervwm,csleb'],
//   ['vodka,clink,haste,nutty,shorn', 'toehh,ckiol,aasvd,nyntu,sknrt'],
//   ['warty,lynch,zesty,dunce,chock', 'wosty,lucne,khrnc,dytce,yhacz'],
//   ['apply,shush,rajah,octal,scalp', 'aprhy,shusl,plcts,ljaaa,hcpoa'],
//   ['downy,ralph,rouge,overt,brick', 'dpwto,ouroh,lyagr,rvben,erick'],
//   ['witty,model,cameo,filer,gawky', 'wlcwm,mieek,taydg,foier,oatly'],
//   ['aware,finch,shirk,whole,trash', 'hlarh,fioch,reask,sanwh,triwe'],
//   ['glare,mulch,aloft,dross,carry', 'glhre,muraa,arsdt,flcor,oclsy'],
//   ['flood,evoke,godly,joist,liver', 'dioof,lvtde,lokey,vriso,gljeo'],
//   ['conch,scent,ruler,slump,bugle', 'conll,scebe,urces,rulmg,nupht'],
//   ['agate,ingot,juice,lilac,husky', 'guicn,oeait,jgahl,eilat,cusky'],
//   ['dowdy,quick,hilly,chord,choke', 'coedi,rhycy,uiclk,dhoqd,lhkow'],
//   ['wooer,canon,wince,botch,funny', 'ienec,caonn,wworo,buthc,fonyn'],
//   ['theme,pasty,ninth,crank,wrist', 'khcme,aatsi,nsrtr,ehpnt,wnyit'],
//   ['blunt,mango,murky,clash,pinto', 'supna,itngo,clylr,mkabh,umnto'],
// ]
